# Generated by Django 2.1b1 on 2018-07-29 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_maker_pmodel_pphoto_product1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Product1'),
        ),
    ]
