# Generated by Django 2.1b1 on 2018-07-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180729_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='nickname',
            field=models.CharField(default='二手机', max_length=15, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='pmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.PModel', verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='出场年份'),
        ),
    ]
